@echo off
echo Iniciando StudyES...
cd /d C:\Users\estef\OneDrive\UBA\StudyES
echo Sincronizando material...
python update_material.py
echo Abriendo StudyES...
start "" "http://localhost:8000"
python server.py
